-- ============================================================
-- CLIMATE CHECKER — SUPABASE SCHEMA
-- Run this in the Supabase SQL Editor to bootstrap the DB.
-- Passwords handled by Supabase Auth (bcrypt server-side).
-- ============================================================

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- 1. PRIVILEGIO (roles)
-- ============================================================
CREATE TABLE IF NOT EXISTS "privilegio" (
    "id"        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nombre"    VARCHAR(255) NOT NULL,
    PRIMARY KEY("id")
);

-- ============================================================
-- 2. PAIS (countries)
-- ============================================================
CREATE TABLE IF NOT EXISTS "pais" (
    "id"            INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nombre"        VARCHAR(255) NOT NULL,
    "url_bandera"   VARCHAR(255) NOT NULL,
    PRIMARY KEY("id")
);

-- ============================================================
-- 3. ESTADO / COMUNIDAD AUTONOMA (states / autonomous communities)
-- ============================================================
CREATE TABLE IF NOT EXISTS "estado_Com_autonom" (
    "id"        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nombre"    VARCHAR(255),
    "id_pais"   INTEGER NOT NULL,
    PRIMARY KEY("id")
);

-- ============================================================
-- 4. CIUDAD (cities)
-- ============================================================
CREATE TABLE IF NOT EXISTS "ciudad" (
    "id"            INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nombreciudad"  VARCHAR(255) NOT NULL,
    "url_bandera"   VARCHAR(255),
    "id_estado"     INTEGER NOT NULL,
    PRIMARY KEY("id")
);

-- ============================================================
-- 5. USUARIO_PANEL_CONTROL
--    Linked to auth.users — password lives in Supabase Auth.
-- ============================================================
CREATE TABLE IF NOT EXISTS "usuario_panel_control" (
    "user_id"        UUID NOT NULL,
    "email"          VARCHAR(255) NOT NULL,
    "privilegio_id"  INTEGER NOT NULL,
    PRIMARY KEY("user_id")
);

-- ============================================================
-- 6. MODERA_PAIS (which roles can moderate which countries)
-- ============================================================
CREATE TABLE IF NOT EXISTS "modera_pais" (
    "id_privilegio" INTEGER NOT NULL,
    "id_pais"       INTEGER NOT NULL,
    PRIMARY KEY("id_privilegio", "id_pais")
);

-- ============================================================
-- 7. API_LINKS (weather API endpoints, stored securely per country)
-- ============================================================
CREATE TABLE IF NOT EXISTS "api_links" (
    "id"        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "url"       VARCHAR(255) NOT NULL,
    "id_pais"   INTEGER NOT NULL,
    PRIMARY KEY("id")
);

-- ============================================================
-- FOREIGN KEYS
-- ============================================================
ALTER TABLE "estado_Com_autonom"
    ADD FOREIGN KEY ("id_pais") REFERENCES "pais"("id") ON DELETE CASCADE;

ALTER TABLE "ciudad"
    ADD FOREIGN KEY ("id_estado") REFERENCES "estado_Com_autonom"("id") ON DELETE CASCADE;

ALTER TABLE "usuario_panel_control"
    ADD FOREIGN KEY ("privilegio_id") REFERENCES "privilegio"("id");

ALTER TABLE "usuario_panel_control"
    ADD FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE "modera_pais"
    ADD FOREIGN KEY ("id_privilegio") REFERENCES "privilegio"("id");

ALTER TABLE "modera_pais"
    ADD FOREIGN KEY ("id_pais") REFERENCES "pais"("id") ON DELETE CASCADE;

ALTER TABLE "api_links"
    ADD FOREIGN KEY ("id_pais") REFERENCES "pais"("id") ON DELETE CASCADE;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE "pais"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE "estado_Com_autonom"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ciudad"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE "privilegio"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usuario_panel_control" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "modera_pais"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_links"           ENABLE ROW LEVEL SECURITY;

-- Public read for reference data
DROP POLICY IF EXISTS "Public read" ON "pais";
CREATE POLICY "Public read" ON "pais"
    FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read" ON "estado_Com_autonom";
CREATE POLICY "Public read" ON "estado_Com_autonom"
    FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read" ON "ciudad";
CREATE POLICY "Public read" ON "ciudad"
    FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read" ON "privilegio";
CREATE POLICY "Public read" ON "privilegio"
    FOR SELECT USING (true);

-- Users can see / update only their own row
DROP POLICY IF EXISTS "Own select" ON "usuario_panel_control";
CREATE POLICY "Own select" ON "usuario_panel_control"
    FOR SELECT USING (auth.uid() = "user_id");
DROP POLICY IF EXISTS "Own insert" ON "usuario_panel_control";
CREATE POLICY "Own insert" ON "usuario_panel_control"
    FOR INSERT WITH CHECK (auth.uid() = "user_id");
DROP POLICY IF EXISTS "Own update" ON "usuario_panel_control";
CREATE POLICY "Own update" ON "usuario_panel_control"
    FOR UPDATE USING (auth.uid() = "user_id");

-- API keys: only authenticated users may read
DROP POLICY IF EXISTS "Auth read" ON "api_links";
CREATE POLICY "Auth read" ON "api_links"
    FOR SELECT USING (auth.role() = 'authenticated');

-- modera_pais: admin-only management
DROP POLICY IF EXISTS "Admin all" ON "modera_pais";
CREATE POLICY "Admin all" ON "modera_pais"
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM "usuario_panel_control" upc
            JOIN "privilegio" p ON upc."privilegio_id" = p."id"
            WHERE upc."user_id" = auth.uid()
              AND p."nombre" = 'admin'
        )
    );

-- ============================================================
-- SEED DATA
-- ============================================================

-- Privilegios / roles
INSERT INTO "privilegio" ("nombre") VALUES
    ('admin'),
    ('editor'),
    ('viewer');

-- Countries
INSERT INTO "pais" ("nombre", "url_bandera") VALUES
    ('España',    'https://flagcdn.com/w320/es.png'),
    ('México',    'https://flagcdn.com/w320/mx.png');

-- States / autonomous communities
INSERT INTO "estado_Com_autonom" ("nombre", "id_pais") VALUES
    ('Andalucía',            (SELECT "id" FROM "pais" WHERE "nombre" = 'España')),
    ('Comunidad de Madrid',  (SELECT "id" FROM "pais" WHERE "nombre" = 'España')),
    ('Cataluña',             (SELECT "id" FROM "pais" WHERE "nombre" = 'España')),
    ('CDMX',                 (SELECT "id" FROM "pais" WHERE "nombre" = 'México')),
    ('Jalisco',              (SELECT "id" FROM "pais" WHERE "nombre" = 'México'));

-- Cities — Sevilla is the placeholder city
INSERT INTO "ciudad" ("nombreciudad", "url_bandera", "id_estado") VALUES
    ('Sevilla',             'https://flagcdn.com/w320/es.png', (SELECT "id" FROM "estado_Com_autonom" WHERE "nombre" = 'Andalucía')),
    ('Málaga',              NULL, (SELECT "id" FROM "estado_Com_autonom" WHERE "nombre" = 'Andalucía')),
    ('Madrid',              NULL, (SELECT "id" FROM "estado_Com_autonom" WHERE "nombre" = 'Comunidad de Madrid')),
    ('Barcelona',           NULL, (SELECT "id" FROM "estado_Com_autonom" WHERE "nombre" = 'Cataluña')),
    ('Ciudad de México',    NULL, (SELECT "id" FROM "estado_Com_autonom" WHERE "nombre" = 'CDMX')),
    ('Guadalajara',         NULL, (SELECT "id" FROM "estado_Com_autonom" WHERE "nombre" = 'Jalisco'));

-- API links (replace YOUR_*_KEY with real keys in production)
INSERT INTO "api_links" ("url", "id_pais") VALUES
    ('https://api.weatherapi.com/v1/current.json?key=YOUR_WEATHERAPI_KEY&q={lat},{lng}', (SELECT "id" FROM "pais" WHERE "nombre" = 'España')),
    ('https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lng}&appid=YOUR_OWM_KEY&units=metric', (SELECT "id" FROM "pais" WHERE "nombre" = 'España')),
    ('https://api.weatherapi.com/v1/current.json?key=YOUR_WEATHERAPI_KEY&q={lat},{lng}', (SELECT "id" FROM "pais" WHERE "nombre" = 'México')),
    ('https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lng}&appid=YOUR_OWM_KEY&units=metric', (SELECT "id" FROM "pais" WHERE "nombre" = 'México'));
